name: test-github-actions

on:
  push:
  
jobs:
  create-dir:
    runs-on: ubuntu-latest

    steps:
      - name: create directory
        run: mkdir test-ak

      - name: list files and dir
        run: ls -al