name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show current directory
        run: pwd

      - name: make a directory
        run: mkdir ak_directory

      - name: List files
        run: ls -la

  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Say Hello
        run: echo "Hello, World!"