name: print var name
on:
    push:

jobs:
    test-var:
        runs-on: ubuntu-latest

        steps:  
            - name: Variables name
              run: |
                echo "repo: $GITHUB_ACTION_REPOSITORY"
                echo "Actor name: $GITHUB_ACTOR"
                echo "Actor Id: $GITHUB_ACTOR_ID"
                echo "env: $GITHUB_ENV"